version: 2.1

parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  dev-orb-version:
    type: string
    default: "dev:int-testing"
  run-integration-tests:
    type: boolean
    default: false

orbs:
  strawberry: hubci/strawberry@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0

executors:
  cimg:
    docker:
      - image: cimg/base:2021.04
  linux:
    machine:
      image: ubuntu-2004:202101-01
  mac:
    macos:
      xcode: 11.7.0

workflows:
  main:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: hubci/strawberry
          alpha-version-ref: "dev:int-testing"
          checkout: true
          attach-workspace: false
          orb-path: orb.yml
          requires:
            - orb-tools/lint
          context: circleci-ctx
      # trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: circleci-ctx
          requires:
            - orb-tools/publish-dev
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # your integration test jobs go here: essentially, run all your orb's
      # jobs and commands to ensure they behave as expected. or, run other
      # integration tests of your choosing
      - integration-test-install:
          matrix:
            parameters:
              runner:
                - cimg
                - linux
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: hubci/strawberry
          add-pr-comment: true
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          requires:
            - integration-test-install
          filters:
            branches:
              only: trunk
          context: circleci-ctx

jobs:
  integration-test-install:
    parameters:
      runner:
        type: executor
        default: cimg
    executor: <<parameters.runner>>
    steps:
      - strawberry/install:
          version: "0.15.0"
      - run:
          name: "Try running Strawberry"
          command: strawberry version
